tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/php'

brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'coreutils'
brew 'findutils'
brew 'bash'

brew 'git'
brew 'tree'
brew 'wget'
brew 'profanity'
brew 'archey'
brew 'vim'
brew 'tmux'